Website/views.py
from flask import Flask, render_template, Blueprint, request, session, flash, redirect, url_for
from .models import Products, Enquiry, Cart
from . import db
from .forms import CheckoutForm

app = Flask(__name__)

bp = Blueprint('main', __name__)

# --------------------------------------Data-----------------------------#

bp = Blueprint('main',__name__)


@bp.route("/")
def home():
    products = Products.query.filter(Products.id<10).all()
    return render_template('home.html', products = products)

@bp.route("/for-sale-products")
def sale():
    forsale = Products.query.filter(Products.sale == 'yes').all()
    return render_template('filterproducts.html', products = forsale, category = "FOR SALE") 



@bp.route('/searched-products/')
def search():
	search = request.args.get('search')
	search = '%{}%'.format(search) # substrings will match
	product = Products.query.filter(Products.description.like(search)).all()
	return render_template('filterproducts.html', products = product, category = 'Search Results')
    


#----------------------------------------------------------SORTING------------------------------------------------------#

@bp.route('/products/<category>', methods = ['POST','GET'])
def sort(category):
    allproducts = Products.query.filter(Products.category == category)
    if request.method == 'POST':
        price = request.values.get('filter')
        sale = request.values.get('sale')
        
        if price == 'priceinc' and sale is None:
            sortedinc = Products.query.filter(Products.category == category).order_by(Products.price)
            return render_template('products.html', items = sortedinc, category = category)
        elif price == 'pricedesc' and sale is None:
            sorteddesc = Products.query.filter(Products.category == category).order_by(Products.price.desc())
            return render_template('products.html', items = sorteddesc, category = category)
        elif sale == 'sale' and price == 'priceinc':
            #if price == 'priceinc':
            inc = Products.query.filter(Products.sale.contains('yes'), Products.category == category)
            sale = inc.order_by(Products.price)
            return render_template('products.html', items = sale, category = category)
        elif sale == 'sale' and price == 'pricedesc':
            desc = Products.query.filter(Products.sale.contains('yes'), Products.category == category)
            sale = desc.order_by(Products.price.desc())
            return render_template('products.html', items = sale, category = category)
        elif sale =='sale':
            psale = Products.query.filter(Products.sale.contains('yes'), Products.category == category)
            return render_template('products.html',items = psale, category = category)
    return render_template('products.html',items = allproducts, category = category)


#----------------------------------------CONTACT--------------------------------------------------#

@bp.route("/contact", methods = ['GET','POST'])
def contact():
    enq = None
    if enq is None:
        enq = Enquiry(firstname = '', lastname = '', email = '', phone = 0, message = '')
    try:
        print(str(enq))
        db.session.add(enq)
        db.session.commit()
    except:
        print('Failed to create the enquiry')

    if request.method == "POST":
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        email = request.form['email']
        phone = request.form['phone']
        message = request.form['message']
        print('The entered details are:\nfirstname: {}\nlastname: {}\nemail: {}\nphone: {}\nmessage: {}'.format(firstname,lastname,email,phone,message))
        enq = Enquiry(firstname = firstname, lastname = lastname, email = email, phone = phone, message = message)
        try:
            db.session.add(enq)
            db.session.commit()
        except:
            print('Failed to save the enquiry')
        return render_template('enquirydone.html', fname = firstname, lname = lastname, email = email, phone = phone, message = message)
    else:
        return render_template('contact.html' )


#----------------------------------------PRODUCTS--------------------------------------------------#

@bp.route("/products/<category>")
def products(category):
    allproducts = Products.query.filter(Products.category == category)
    return render_template('products.html', items = allproducts, category = category)


#----------------------------------------PRODUCTS DETAILS--------------------------------------------------#

@bp.route("/products/<int:pid>/<pcat>/<pname>/<pimg>/<pprice>")
def details(pid,pname,pcat,pimg,pprice):
    return render_template('productdetails.html',pid = pid, pname = pname, pcat = pcat, pimg = pimg, pprice = pprice)


#----------------------------------------SHOPPING CART--------------------------------------------------#

@bp.route("/shoppingcart", methods = ['POST','GET'])
def addtocart():

    product_id = request.values.get('product_id')  
    size = request.values.get('options')
    qty = request.values.get('qty')
  
    # retrieve products in cart 
    if 'cart_id' in session.keys():
        cart = Cart.query.get(session['cart_id'])

    else: # The cart is empty
        cart = None

    # Create a shopping cart for products
    if cart is None:
        cart = Cart(status = False, firstname = '',lastname = '',email = '', phone = '', no_of_items = 0, total_cost = 0)
        try:
            db.session.add(cart)
            db.session.commit()
            session['cart_id'] =  cart.id
        except:
            print('failed to create a shopping cart')
            cart = None

    
# calculating total price
    totalprice = 0
    if cart is not None:
        for product in cart.products:
            totalprice = totalprice + (product.price * product.qty)

# calculating total items
    totalitems = 0
    if cart is not None:
        for product in cart.products:
            totalitems += 1

# Shipping charges
    shipping = 0
    if totalitems != 0:
        shipping = 10


   
 # adding a product     
    if product_id is not None and cart is not None:
        product = Products.query.get(product_id) 
        
        if product not in cart.products:   
            
            try:
                product.qty = qty
                Products.stock = Products.stock - qty
                product.size = size
                cart.products.append(product)
                db.session.add(cart)
                db.session.commit()
                
                    
            except:
                return 'There was some issue adding the product in the basket'
            return redirect(url_for('main.addtocart'))    

        else:
            flash('The product is already in the basket')
            return redirect(url_for('main.addtocart'))
    return render_template('cart.html', cart = cart, totalprice = totalprice, totalitems = totalitems, shipping = shipping)
         


#------------------------------------------Empty the Cart-----------------------------------------------------#

@bp.route("/emptycart")
def emptycart():
    if 'cart_id' in session:
        del session['cart_id']
        flash('All items deleted.')
    return redirect(url_for('main.home'))    


#---------------------------------------Remove an item from cart-----------------------------------------------#

@bp.route("/deleteditem/", methods =['POST'])
def deleteitem():
    id = request.form.get('id')
    if 'cart_id' in session:
        cart = Cart.query.get_or_404(session['cart_id'])
     
        deleteproduct = Products.query.get(id)
        print(deleteproduct)
        try:
            cart.products.remove(deleteproduct)
            db.session.commit()
            return redirect(url_for('main.addtocart'))
        except:
            return 'Problem deleting the item from Cart'
    return redirect(url_for('main.addtocart'))



#------------------------------------------------Checkout Form-------------------------------------------------------#

@bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'cart_id' in session:
        cart = Cart.query.get_or_404(session['cart_id'])
       
        if form.validate_on_submit():
            cart.status = True
            cart.firstname = form.firstname.data
            cart.lastname = form.lastname.data
            cart.email = form.email.data
            cart.phone = form.phone.data
            cart.address = form.address.data
            totalcost = 0
            for product in cart.products:
                totalcost = totalcost + product.price
            cart.totalcost = totalcost
            try:
                db.session.add(cart)
                db.session.commit()
                del session['cart_id']
                flash('Order Placed! Thank you for placing your order.')
                return redirect(url_for('main.home'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form = form)



  

Website/templates/base.html
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="utf-8">
    <meta name="description" content="Bazinga - The Merchandise Store">
    <title>Bazinga - The Merchandise Store</title>
    <link rel="icon" href="{{ url_for('static', filename = 'img/icon.png  ') }}" type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
   <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">

   {% block head %}
   {% endblock %}

</head>
<body>
    <header>
        <nav id="navbar" class="navbar navbar-inverse">
            <div id="navigationbar" class="container-fluid">
              <div id="companyname" class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('main.home')}}" style="font-weight: bold;"><img class="d-inline-block align-top" id ="logo" alt="" src = "{{url_for('static', filename = 'img/logo1.png')}}"></a>
              </div>
              <ul id="menu" class="nav navbar-nav">
               
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="Menfashion.html">MEN
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('main.products', category = 'T-SHIRTS') }}">T-Shirts</a></li>
                    <li><a href="{{ url_for('main.products', category = 'HOODIES') }}">Hoodies/Jackets</a></li>
                    <li><a href="{{ url_for('main.products', category = 'SHOES') }}">Shoes</a></li>
                  </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="Womenfashion.html">WOMEN
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="{{ url_for('main.products', category = 'TOPS') }}">Tops</a></li>
                      <li><a href="{{ url_for('main.products', category = 'LEGGINGS') }}">Legging/Jegging</a></li>
                      <li><a href="{{ url_for('main.products', category = 'SKIRTS') }}">Skirts</a></li>
                      
                    </ul>
                  </li>

                  <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">EXTRAS
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu"> 
                      <li><a href="{{ url_for('main.products', category = 'BAGS') }}">Bags</a></li>
                      <li><a href="{{ url_for('main.products', category = 'PERFUMES') }}">Perfumes</a></li>
                      <li><a href="{{ url_for('main.products', category = 'COLLECTABLES') }}">Collectables</a></li>
                
                    </ul>
                    <li id="contact"><a href="{{ url_for('main.sale')}}">FOR SALE</a></li>
                  <li id="contact"><a href="{{ url_for('main.contact')}}">CONTACT US</a></li>

              </ul>     

              <div id="rightnavbar">
                  <ul class="nav navbar-nav navbar-right">
                    <form id="search" class="navbar-form navbar-left" action="{{ url_for('main.search') }}">
                        <div class="input-group">
                          <input  type="text" class="form-control" placeholder="What are you looking for?" name = "search">
                          <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                              <i class="glyphicon glyphicon-search"></i>
                            </button>
                          </div>
                        </div>
                      </form>
              
                <li><a href="{{ url_for('main.addtocart') }}"><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
              </ul>
              </div>
            </div>
          </nav>
    </header>
  <br>  <!--------------------Main Body---------------------->


  {% with messages = get_flashed_messages() %}
  {% if messages %}
      <div class="alert alert-primary" role="alert">
      {% for message in messages %}
      {{ message }}
      {% endfor %}
      </div>
  {% endif %}
  {% endwith %}



<section>
{% block main %}
{% endblock %}
</section>
    <br>
<footer id="footer">
        <div style="color: white; text-align: center; ">
          <br>
          Copyright&nbsp;&copy;&nbsp;2020 Bazinga. All Rights Reserved. </span>
      </div>
      </footer>
</body>
</html>

Website/templates/cart.html
{% extends 'base.html' %}

{% block head %}

<style>
h1{
    text-align: center;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: 55px;
    font-weight: bolder;
    color: rgb(77, 72, 72);
    margin-top: 50px;

 }

 img{

    height: 250px;
    width: 200px;
    object-fit: cover;
 }

 #leftrow{border: rgb(230, 230, 230) solid 1px; padding: 20px;}

 #pname{

font-size: 18px;
font-family: 'Trebuchet MS';
margin-top: 5px;
 }

 #pcategory{
     font-size: 14px;
     font-family: 'Trebuchet MS';
     margin-top: 5px;
     
 }

 #psize{
     font-size: 16px;
     font-family: 'Trebuchet MS';
     margin-top: 30px;
     
 }

 #pqty{

font-size: 16px;
 font-family: 'Trebuchet MS';
 margin-top: 20px;
}

 #pprice{

    font-size: 20px;
     font-family: 'Trebuchet MS';
     margin-top: 20px;
 }

 #checkout{
    padding: 10px;
    margin-left: 13px;
    padding-left: 95px;
    padding-right: 92px;
 }

 #empty{

    padding: 9px;
    padding-left: 20px;
    padding-right: 20px;
    margin-left: 120px;


 }

 #total{margin-left: 30px; margin-right: 20px; padding: 16px; font-size: 15px; border: rgb(199, 198, 198) solid 2px; }

 #gst{margin-left: 30px; margin-right: 20px; margin-top: -2px; padding: 16px; font-size: 15px; border: rgb(199, 198, 198) solid 2px;}

 #shipping{margin-left: 30px; margin-right: 20px; margin-top: -2px; padding: 16px; font-size: 15px; border: rgb(199, 198, 198) solid 2px;}

 #totalpay{margin-left: 30px; margin-right: 20px; margin-top: -2px; padding: 16px; font-size: 15px; border: rgb(199, 198, 198) solid 2px;}

 
 
 </style>
{% endblock %}

{% block main %}

<div class="container-fluid" style="background-color: rgb(204, 204, 204); height: 180px ;"> <h1>Shopping Cart</h1></div>
<br><br><br>
<div class = "container">
    <div class="col-sm-8">
        <div class="row">
        <div style="margin-top: 7px;" class="col-sm-8"><b style="font-family: 'Trebuchet MS'; font-size: 18px; ">Items ({{ totalitems }})</b></div>

       <div class = "col-sm-4"><a href="{{ url_for('main.emptycart') }}"> <button id="empty" type="button" class="btn btn-danger">Empty Cart</button></a></div>
</div>
       <br>
        {% for product in cart.products %}
        <div id = "leftrow"class="row">
            <div class="col-sm-4">
                <img src = "{{ url_for('static', filename ='img/' + product.image)}}">
            </div>
            <div class="col-sm-8">
                <b id="pname">{{ product.name }}</b> <p id ="pcategory">{{ product.category }} </p> <br>
                <p><b id = "psize">Size&nbsp;-&nbsp;{{ product.size }} </b></p>
                <p><b id = "pqty">Qty&nbsp;-&nbsp;{{ product.qty }}</b></p> <b id="pprice"> ${{ product.price * product.qty }}</b>
                <br><br>
                <form method ="POST" action = "{{ url_for('main.deleteitem')}}">
                    <input type ="hidden" name="id" id="id" value="{{ product.id }}">
                    <input type ="submit" value="Remove Item" class="btn btn-secondary">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="col-sm-4" style="padding: 5px; ">
<br><br><br>
        <div class="row">
            <center> <p style="font-family: Verdana, Geneva, Tahoma, sans-serif; color: rgb(94, 90, 90); font-weight: bold; font-size: 30px;">Billing Details</p></center>
         </div>
         <hr>
         <div id ="total" class="row">
            <div class="col-sm-9"> Cart Total &nbsp; </div> <div class="col-sm-3">{{ "$%.2f"|format(totalprice) }} </div>
         </div>
         <div id="gst" class="row">
            <div class="col-sm-9">GST &nbsp;(18%) </div> <div class="col-sm-3">{{ "$%.2f"|format(totalprice * 0.18) }} </div>
        </div>
        <div id="shipping" class="row">
            <div class="col-sm-9"> Shipping Charges &nbsp; </div> <div class="col-sm-3"> {{ "$%.2f"|format(shipping) }} </div>
        </div>
        <div id="totalpay" class="row">
            <div class="col-sm-9"> <b>Total Payable</b> &nbsp; </div> <div class="col-sm-3"><b> {{ "$%.2f"|format((totalprice) + (totalprice*0.18) + shipping) }}</b> </div>
        </div>
        <br>
        <div class="row">
           <center> <a href ="{{ url_for('main.checkout') }}"> <button id="checkout" type="button" class="btn btn-primary">Proceed to Checkout</button></a></center>
           <br>
          
           
        </div>
        <br>
        
        
    </div>
</div>

{% endblock %}

Website/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
<style>
h1{
    text-align: center;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: 55px;
    font-weight: bolder;
    color: rgb(77, 72, 72);
    margin-top: 50px;

 }

#checkout{
 margin-left: 200px; 
 background-color: rgb(212, 203, 252);
 padding: 40px;
 font-family: 'Trebuchet MS';
 font-size: 18px;
}
</style>
{% endblock %}

{% block main %}
    <section>  
        <div class="container-fluid" style="background-color: rgb(204, 204, 204); height: 180px ; "> <h1>Checkout</h1></div>
        <div class="container">
            
            <div class="row">
                <div class = "col-12">
                    <br>
                    <p style="font-family: 'Trebuchet MS'; font-size: 22px; text-align: center; margin-top: 20px; margin-bottom: 20px;">
                        <u>Thank you for your interest. Please provide your details down below to complete your order. Thank you! </u>
                    </p>
                </div>
            </div>
            <br>
            <div class="row">
                <div id = "checkout" class = "col-sm-8" >
                    {{wtf.quick_form(form)}}
                </div>
            </div>
        </div>
    </section>
    <br><br>
{% endblock %}

Website/templates/contact.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/enquiry1.css') }}">
{% endblock %}


{% block main %}


<h1 >Contact Us</h1>
<br><br>
    <div class="container">
        <form action ="#" method="POST">
            <br>
          <label id="form" for="fname" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 17px;">First Name</label>
          <br>
          <input id="contact1" type="text" id="fname" name="firstname" placeholder="Your first name..">
            <br>
          <label id="form" for="lname" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 17px;">Last Name</label>
          <br>
          <input id="contact1" type="text" id="lname" name="lastname" placeholder="Your last name..">
         <br>
         <label id="form" for="email" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 17px;">Email ID</label>
          <br>
          <input id="contact1" type="email" id="email" name="email" placeholder="Your email id..">
         <br>
         <label id="form" for="phone" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 17px;">Phone No</label>
          <br>
          <input id="contact1" type="text" id="phone" name="phone" placeholder="Your phone no..">
         <br>
          <!-- <label id="form" for="state" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 17px;">State</label>
          <br>
         <select id="city" name="State">
            <option value="NT">Northern Territory</option>
            <option value="WA">Western Australia</option>
            <option value="VIC">Victoria</option>
            <option value="NSW">New South Wales</option>
            <option value="QLD">Queensland</option>
            <option value="SA">South Australia</option>
          </select>
         <br> -->
          <label id="form" for="message" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-size: 17px;">Message</label>
          <br>
          <input id="contact1" type="text" id="message" name="message" placeholder="Please write here.." >
      <br><br>
          <input type="submit" value="Submit">
      
        </form>
      </div>

      <br><br>

{% endblock %}

Website/templates/filterproducts.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/products1.css') }}">
{% endblock %}

{% block main %}

<div class="container-fluid" style="background-color: rgb(218, 218, 218); height: 180px ;"> <h1>{{category}}</h1></div>
<br><hr><br>
<div class = "container-fluid" style="padding-left: 80px; padding-right: 80px;">
{% for product in products %}

            <div class="col-sm-4">
                 <figure>
                      <a href="{{ url_for('main.details', pid = product.id, pname = product.name, pcat = product.category, pimg= product.image, pprice = product.price) }}">
                      <img id="img" src="{{ url_for('static', filename='img/' + product.image) }}" width="100%" height="450px" style="border-style: solid; border-width: 8px; border-color: lightslategray;">  
                  </a>
                  <figcaption> {{ product.name }}
                  </figcaption>
                  <hr style="margin-top: 4px;" id="captionhr" width="90%">
                  
                      <h4 style="font-weight: bolder; font-size: 15px; margin-top: -10px;">$ {{ product.price }}</h4>
      
                  </figure>
            </div>
        
              {% endfor %}
              </div>
<br>
{% endblock %}

Website/templates/home.html
{% extends 'base.html' %}

{% block main %}
    <!--------------------Main Body---------------------->

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>
      
     
        <div class="carousel-inner">
          <div class="item active">
            <img src="{{ url_for('static', filename='img/carousel-1.jpg') }}" alt="Video Games Collectables">
            <div class="carousel-caption">
              <h3>Video Games Collectables</h3>
              <p>Shop your favourite Video-Games collection</p>
            </div>
          </div>
      
          <div class="item">
            <img src="{{ url_for('static', filename='img/carousel-2.jpg') }}" alt="Men's Fashion">
            <div class="carousel-caption">
              <h3>Men's Fashion</h3>
              <p>Be up to the mark</p>
            </div>
          </div>
      
          <div class="item">
            <img src="{{ url_for('static', filename='img/carousel-3.jpg') }}" alt="Women's Fashion">
            <div class="carousel-caption">
              <h3>Women's Fashion</h3>
              <p>Be gorgeous all the time</p>
            </div>
          </div>

          <div class="item">
            <img src="{{ url_for('static', filename='img/carousel-4.jpg') }}" alt="Super-Heros" style="object-fit: contain;">
            <div class="carousel-caption">
              <h3>Accessories</h3>
              <p>Shop your favourite branded accessory</p>
            </div>
          </div>
        </div>
      
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>

      <section id="Products">
        <br><br>
        <h3 style="text-align: center; font-size: 26px; font-weight: bold;
         font-family: Arial, Helvetica, sans-serif; color: gray;">
         -------------------------------------------------------------&nbsp;&nbsp;&nbsp;&nbsp;PRODUCTS&nbsp;&nbsp;&nbsp;&nbsp;------------------------------------------------------------------
      </h3>
          <br>
       <div class="container-fluid">

{% for product in products %}
       
        <div class="col-sm-4" >
          <a href="{{ url_for('main.products', category = product.category) }}">
          <img id="img1" src="{{ url_for('static', filename='img/'+ product.image) }}" width="100%" height="500px" alt="{{ product.category }}" >
          <div class="bottom-left">{{ product.category }}</div>
          </a>
        </div>
    
{% endfor %}

      </div>
        <br>
{% endblock %}

Website/templates/products.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/products1.css') }}">
{% endblock %}

{% block main %}
<div class="container-fluid" style="background-color: rgb(218, 218, 218); height: 180px ;"> <h1>{{ category }}</h1></div>
      <br>
      <hr>
      <br>
      <div class="container-fluid">
          <div class="row">
              <div id= "filter" class="col-sm-3">

      <br>
      <form method = "POST" action= "{{ url_for('main.sort', category = category) }}">

        <br>
                 <h3 id="sort">Sort</h3>
                 <hr style="margin-top: 6px;">
                  <div class="custom-control custom-radio">
                      <input type="radio" id="customRadio1" name="filter" class="custom-control-input" value = "priceinc">
                      <label id="radio" class="custom-control-label" for="customRadio1">Price - Low to High</label>
                  </div>
                    
                  <div  class="custom-control custom-radio">
                      <input type="radio" id="customRadio2" name="filter" class="custom-control-input" value = "pricedesc">
                      <label id="radio" class="custom-control-label" for="customRadio2">Price - High to Low</label>
                      
         <br><br>             
                      <h3 id="sort">Offers</h3>
                      <hr style="margin-top: 6px;">
                      <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck3" name = "sale" value = "sale">
                        <label id="checkbox" class="custom-control-label" for="customCheck3">For Sale</label>
                      </div>
<br>
                      <div id = "submit">
                      <button type ="button" class = "btn btn-primary" role="button" >
                        <input class = "btn btn-primary" type = "submit" value = "Apply Filter">
                      </button>
                    </div>
                    </div>
                  </form>
                  </div>
                
      <!------------------------------------------Products-------------------------------------------------->
             <div class="col-sm-9"> 
        {% for product in items %}
            <div class="col-sm-3">
                 <figure>
                      <a href="{{ url_for('main.details', pid = product.id, pname = product.name, pcat = product.category, pimg= product.image, pprice = product.price) }}">
                      <img id="img" src="{{ url_for('static', filename='img/' + product.image) }}" width="100%" height="370px" style="border-style: solid; border-width: 8px; border-color: lightslategray;">  
                  </a>
                  <figcaption> {{ product.name }}
                  </figcaption>
                  <hr style="margin-top: 4px;" id="captionhr" width="90%">
                  
                      <h4 style="font-weight: bolder; font-size: 15px; margin-top: -10px;">$ {{ product.price }}</h4>
      
                  </figure>
            </div>
              {% endfor %}
              </div>
          </div>
      </div>
{% endblock %}